#!/bin/bash

# generate static code
bundle exec middleman build

#generate optimized capps
pushd build/en
jake deploy
popd

pushd build/jp
jake deploy
popd

# pull the old repository
git clone git@github.com:bunnylabs/bunnylabs.github.io

# add and push new content
pushd bunnylabs.github.io
git config --global user.email "davidsiaw@gmail.com"
git config --global user.name "David Siaw (via Travis CI)"
git config --global push.default simple
rm -r *
cp ../build/* .
mkdir -p en
cp -r ../build/en/Build/Release/BunnyLabs/* en/
mkdir -p jp
cp -r ../build/jp/Build/Release/BunnyLabs/* jp/
git add *
git add -u
git commit -m "Update site"
git push
popd

# cleanup
rm -rf bunnylabs.github.io
